### ISSUE TITLE
 errors trying to run it locally

### ISSUE THREAD

**Issue by elkizana** [yuqian5/parkour#2]
I got errors trying to run it locally 

![Screenshot from 2023-11-29 19-37-16](https://github.com/yuqian5/parkour/assets/53874333/f9c83d24-7697-43bd-ba71-1d91d3cd3086)

**Comment by yuqian5** [comment]
Did you run it with the command `npm start dev`

**Comment by elkizana** [comment]
![Screenshot from 2023-11-30 15-14-21](https://github.com/yuqian5/parkour/assets/53874333/9e20f724-6806-4b55-a40e-432673c5814e)

**Comment by elkizana** [comment]
resolved by adding :  `"start": "vite ."  `
 under scripts in package.json 
than : npm start dev 
thanks
